/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as FormulasIndexImport } from './routes/formulas/index'
import { Route as FormulasNewImport } from './routes/formulas/new'
import { Route as FormulasIdIndexImport } from './routes/formulas/$id/index'
import { Route as FormulasIdEditImport } from './routes/formulas/$id/edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FormulasIndexRoute = FormulasIndexImport.update({
  id: '/formulas/',
  path: '/formulas/',
  getParentRoute: () => rootRoute,
} as any)

const FormulasNewRoute = FormulasNewImport.update({
  id: '/formulas/new',
  path: '/formulas/new',
  getParentRoute: () => rootRoute,
} as any)

const FormulasIdIndexRoute = FormulasIdIndexImport.update({
  id: '/formulas/$id/',
  path: '/formulas/$id/',
  getParentRoute: () => rootRoute,
} as any)

const FormulasIdEditRoute = FormulasIdEditImport.update({
  id: '/formulas/$id/edit',
  path: '/formulas/$id/edit',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/formulas/new': {
      id: '/formulas/new'
      path: '/formulas/new'
      fullPath: '/formulas/new'
      preLoaderRoute: typeof FormulasNewImport
      parentRoute: typeof rootRoute
    }
    '/formulas/': {
      id: '/formulas/'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasIndexImport
      parentRoute: typeof rootRoute
    }
    '/formulas/$id/edit': {
      id: '/formulas/$id/edit'
      path: '/formulas/$id/edit'
      fullPath: '/formulas/$id/edit'
      preLoaderRoute: typeof FormulasIdEditImport
      parentRoute: typeof rootRoute
    }
    '/formulas/$id/': {
      id: '/formulas/$id/'
      path: '/formulas/$id'
      fullPath: '/formulas/$id'
      preLoaderRoute: typeof FormulasIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/formulas/new': typeof FormulasNewRoute
  '/formulas': typeof FormulasIndexRoute
  '/formulas/$id/edit': typeof FormulasIdEditRoute
  '/formulas/$id': typeof FormulasIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/formulas/new': typeof FormulasNewRoute
  '/formulas': typeof FormulasIndexRoute
  '/formulas/$id/edit': typeof FormulasIdEditRoute
  '/formulas/$id': typeof FormulasIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/formulas/new': typeof FormulasNewRoute
  '/formulas/': typeof FormulasIndexRoute
  '/formulas/$id/edit': typeof FormulasIdEditRoute
  '/formulas/$id/': typeof FormulasIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/formulas/new'
    | '/formulas'
    | '/formulas/$id/edit'
    | '/formulas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/formulas/new'
    | '/formulas'
    | '/formulas/$id/edit'
    | '/formulas/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/formulas/new'
    | '/formulas/'
    | '/formulas/$id/edit'
    | '/formulas/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FormulasNewRoute: typeof FormulasNewRoute
  FormulasIndexRoute: typeof FormulasIndexRoute
  FormulasIdEditRoute: typeof FormulasIdEditRoute
  FormulasIdIndexRoute: typeof FormulasIdIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FormulasNewRoute: FormulasNewRoute,
  FormulasIndexRoute: FormulasIndexRoute,
  FormulasIdEditRoute: FormulasIdEditRoute,
  FormulasIdIndexRoute: FormulasIdIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/formulas/new",
        "/formulas/",
        "/formulas/$id/edit",
        "/formulas/$id/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/formulas/new": {
      "filePath": "formulas/new.tsx"
    },
    "/formulas/": {
      "filePath": "formulas/index.tsx"
    },
    "/formulas/$id/edit": {
      "filePath": "formulas/$id/edit.tsx"
    },
    "/formulas/$id/": {
      "filePath": "formulas/$id/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
